---

- name: say hi
  shell: "echo 'ABY WELCOME'; whoami"

- name: clone fresco repository
  git: 
    repo: https://github.com/aicis/fresco.git
    dest: /src/fresco/
    force: yes
  become_user: "{{user}}"

# - name: make install fresco
#   shell: "mvn install -DskipITs"
#   args: 
#     chdir: /src/fresco
#   environment:
#     PATH: /src/{{maven_version}}/bin:{{ ansible_env.PATH }}
#   become_user: "{{user}}"
