---

- name: install dependencies
  apt: name={{item}} state=installed
  with_items:
    - g++
    - make
    - git
    - libmsgpack-dev

- name: create src folder
  file: path=/src/ state=directory owner={{user}} group={{user}} mode=0775 recurse=yes

  
- name: clone justGarble
  git: 
    repo: https://github.com/irdan/justGarble.git
    dest: /src/justGarble/
    force: true
  become_user: "{{ user }}"

- name: create neccessary folder for justGarble
  file: 
    path: "/src/justGarble/{{ item }}"
    state: directory 
    owner: "{{user}}"
    group: "{{user}}" 
    mode: 0775 
    recurse: yes
  with_items:
    - bin
    - obj
  become_user: "{{ user }}"