---

- name: install dependencies
  apt: name={{item}} state=installed
  with_items:
    - g++
    - make
    - git
    - libgmp3-dev
    - libglib2.0-dev
    - libboost-all-dev
    - libssl-dev
    - libssl-ocaml-dev
    - wget
    - apt-utils

- name: sym link library
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    state: link
  with_items:
    - { src: '/lib/x86_64-linux-gnu/libssl.so.1.0.0', dest: '/lib/x86_64-linux-gnu/libssl.so.10' }
    - { src: '/lib/x86_64-linux-gnu/libcrypto.so.1.0.0', dest: '/lib/x86_64-linux-gnu/libcrypto.so.10' }
    - { src: '/usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0', dest: '/usr/lib/libgmp.so.3'}

- name: create src folder
  file: path=/src/ state=directory owner={{user}} group={{user}} mode=0775 recurse=yes

- name: clone tinygarble
  git:
    repo: https://github.com/esonghori/TinyGarble.git
    recursive: false
    force: true
    dest: /src/tinygarble

- command: ./configure
  args:
    chdir: /src/tinygarble
  
- command: make
  args:
    chdir: /src/tinygarble/bin

  