---

- name: install dependencies
  apt: name={{item}} state=installed
  with_items:
    - g++
    - make
    - git
    - autoconf
    - automake
    - libtool
    - curl
    - unzip

- name: create src folder
  file: path=/src/ state=directory owner={{user}} group={{user}} mode=0775 recurse=yes

- name: clone repository
  git: 
    repo: https://github.com/google/protobuf.git
    dest: /src/protobuf/
    force: yes
  become_user: "{{user}}"

- name: make protobuf
  shell: >
    ./autogen.sh && ./configure --prefix=/usr && make && make check
  args:
    chdir: /src/protobuf/
  become_user: "{{user}}"

- shell: >
    make install && ldconfig
  args:
    chdir: /src/protobuf/

