---

- name: install dependencies
  apt: name={{item}} state=installed
  with_items:
    - g++
    - make
    - git

- name: create src folder
  file: path=/src/ state=directory owner={{user}} group={{user}} mode=0775 recurse=yes


- name: clone emp
  git: 
    repo: https://github.com/emp-toolkit/emp-readme.git
    dest: /src/emp-readme/
    force: true
    recursive: no
  become_user: "{{ user }}"

- name: install emp
  command: "bash ./scripts/setup_new_machine.sh"
  args:
    chdir: /src/emp-readme/