---

- name: create src folder
  file: path=/src/ state=directory owner={{user}} group={{user}} mode=0775 recurse=yes



- name: clone oblivm repository
  git: 
    repo: "https://github.com/oblivm/ObliVMLang.git"
    dest: /src/oblivm/
    force: yes
  become_user: "{{user}}"

- name: compile oblivm
  command: "sh ./compile.sh"
  args:
    chdir: /src/oblivm/

# - name: make install fresco
#   shell: "mvn install -DskipITs"
#   args: 
#     chdir: /src/fresco
#   environment:
#     PATH: /src/{{maven_version}}/bin:{{ ansible_env.PATH }}
#   become_user: "{{user}}"
